### PR TITLE
vendor/skyspark: Add new function to execute Eval op using POST.

### PR DESCRIPTION
**Pull request by criverc**
As GET is deprecated in Skyspark > 3.0.20.

### CODE REVIEW

**Comment by criverc** [comment]
I mean http GET is deprecated on ops that may have side effects, like eval.

**Comment by ChristianTremblay** [comment]
Thanks for that, I'll have a look ASAP.

**Comment by ChristianTremblay** [comment]
Many thanks @criverc

**Comment by criverc** [comment]
> Many thanks @criverc

Thanks to you for accepting my patch :-)

**Pull request merged**
