### PR TITLE
Issue #103: util.state: Implement __await__ and .future

### LINKED ISSUE #103: Implement __await__ on operation classes
So, been thinking about this for a long while now.  We have the necessary bits for asynchronous operations, and yes, it's on my to-do list to write an async HTTP client implementation.  Modern `ipython` (and probably Jupyter notebook too) supports the `await` keyword.

It'd be real nice to be able to run:
```python
res = await client.his_read_frame(…etc…)
```

Turns out, this _can_ be done, with a little work on our end:
https://docs.python.org/3.5/library/collections.abc.html#collections.abc.Awaitable

We'd need to implement (in Python 3.5+ only):
```python
class HaystackOperation(object):
    if CAN_PYTHON_AWAIT:
        def __await__(self):
            future = Future()
            def _on_done(*args, **kwargs):
                try:
                    future.set_result(self.result)
                except Exception as ex:
                    future.set_exception(ex)
            self.done_sig.connect(_on_done)
            return future
```

This is untested of course, and we'd need to write some code to detect if we're on Python 3.5+ since this won't work on anything older.  That has the potential though to make a _much_ nicer experience for users, particularly interactive users.

### PR DESCRIPTION
**Pull request by sjlongland**
`.future` returns a `Future` object (either a native `asyncio` `Future`,
or a Tornado `Future`), which can be `yield`-ed (Tornado on Python <3.4)
or `await`-ed (Python 3.5+).

TODO: Some unit tests.

### CODE REVIEW

**Comment by ChristianTremblay** [comment]
@sjlongland it was tagged as "draft" , can we merge ?

**Comment by sjlongland** [comment]
On 1/12/20 11:28 am, Christian Tremblay wrote:
> @sjlongland it was tagged as "draft" , can we merge ?

I'd like to try and get some unit tests in there first.  Make sure it
works as it should.

**Comment by sjlongland** [comment]
Okay, let's see what Travis CI makes of this.  Works fine on Gentoo with Python 2.7.18 and Python 3.8.6.

**Comment by ChristianTremblay** [comment]
Keeping state.py for compatibility ? Not sure how this will be called (I don't get the assert...)

**Comment by ChristianTremblay** [comment]
Another question, just to be sure, if we want this to work, we'll need an async requests gizmo ? You set up the base, right ?

**Comment by sjlongland** [comment]
On 20/12/20 7:02 am, Christian Tremblay wrote:
> Keeping state.py for compatibility ? Not sure how this will be called (I don't get the assert...)

Well, sort-of.  I tried to do it all in `state.py`, but Python 2 threw a
hissy fit over the `await` and `async` keywords.  This is primarily a
Python 3 feature, but I don't want to break Python 2 yet (even though
I've told my workplace I won't be writing Py2 code from 2020 onwards).

So I was forced to put it in a separate "module" to "hide" it.  It
checks what version of Python is before importing.  That said, just
realised I should try actually installing the package too.

Same deal with the tests, you'll see I did the same thing there.

All the `assert` does is keep `pyflakes` from complaining that a symbol
is imported but not used.

**Comment by sjlongland** [comment]
On 20/12/20 7:04 am, Christian Tremblay wrote:
> Another question, just to be sure, if we want this to work, we'll need an async requests gizmo ? You set up the base, right ?

Yeah, that's the other half of the equation, asynchronous HTTP client
glue logic.  There's `aiohttp` on Python 3.4+.  Tornado also has an
`async` client we could wrap.

Again, I'll put these in their own modules so that they're "hidden" from
Python installs that can't understand the syntax (`yield from`/`await`).

My primary aim in this PR was to make the operations in `ipython` shell
more "natural" by making its `async` support handle `pyhaystack`'s way
of doing async operations.

**Comment by sjlongland** [comment]
Okay, so that last commit takes care of this:
```
byte-compiling build/bdist.linux-x86_64/egg/pyhaystack/util/filterbuilder.py to filterbuilder.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyhaystack/util/asyncexc.py to asyncexc.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyhaystack/util/tools.py to tools.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyhaystack/util/awaitableop.py to awaitableop.pyc
  File "build/bdist.linux-x86_64/egg/pyhaystack/util/awaitableop.py", line 20
    res = yield from self.future
                   ^
SyntaxError: invalid syntax
```

I've moved `awaitableop` into the `pyhaystack.util.awaitable` sub-package.  Python 2.7 users, it'll omit `pyhaystack.util.awaitable`, everyone else, it includes it.

**Comment by ChristianTremblay** [comment]
Going forward.... it is a tremendous improvement for what will happen next !

**Pull request merged**
