### PR TITLE
simplifying grid_format parameter

### PR DESCRIPTION
**Pull request by duduklein**

### CODE REVIEW

**Comment by duduklein** [comment]
That's interesting. Removing useless lines made coverage decrease, which could be seen as a bad thing.

**Comment by sjlongland** [comment]
On 17/10/19 11:02 am, Christian Tremblay wrote:
> *@ChristianTremblay* commented on this pull request.
> 
> What would you think if we would simplify it in regard to user...and not 
> the code.
> 
> |def __init__(self, uri, username, password, grid_format='json', **kwargs): |
> 
> I think we can get rid of the hszinc... in fact hszinc.MODE_JSON = 
> 'json' :-)

… which will break if `hszinc` decides to use the Enum class. :-)

**Comment by ChristianTremblay** [comment]
Party breaker ! ;-)

What I would like is “not having” to import hszinc if you use pyhaystack
and want to specify the grid format.

Actually we need it which is not optimal. What do you think ?



Le mer. 16 oct. 2019 à 21:04, Stuart Longland <notifications@github.com> a
écrit :

**Comment by sjlongland** [comment]
Well, one option is that the `pyhaystack` module mirrors the `hszinc` `MODE_JSON` and `MODE_ZINC` options.  For what it's worth changing their values would probably break a lot of in-house stuff too. :-)

If we added:
```
from hszinc import MODE_JSON, MODE_ZINC
```

to the top of `pyhaystack`'s top-level `__init__.py`, that would avoid the need to import an additional module, regardless of what happened upstream.

**Comment by ChristianTremblay** [comment]
Safest way would probably look like : 

```
import hszinc
def __init__(self, uri, username, password, grid_format='json', **kwargs):
    grid_format = get_format(grid_format)
    [...]

def get_format(grid_format, default=hszinc.MODE_JSON):
    gf = grid_format.lower()
    if isinstance(grid_format, str):
        if gf == 'json' or gf == hszinc.MODE_JSON:
            return hszinc.MODE_JSON
        elif gf == 'zinc' or gf == hszinc.MODE_ZINC:
            return hszinc.MODE_ZINC
    else:
        return default
```

**Comment by duduklein** [comment]
@ChristianTremblay , IMO you are complicating something that should be very simple. What I suggested is the standard way of handling default parameters. 

The solution proposed by @sjlongland to import the modes themselves `from hszinc import MODE_JSON, MODE_ZINC` instead of the whole module is also good, since it removes the issue about those modes being numbers, string, enums or other thing. Passing `grid_format=MODE_JSON` is a good solution.

Do you have a use case that would justifies all this "headache"? pyhaystack depends anyway on hszinc, so I don't see any good reason to not to use the "proper" modes from hszinc directly.
We could even include an assert statement to make sure the grid_format mode is valid :
`assert grid_format in [MODE_ZINC, MODE_JSON]` (I think I saw this somewhere in the code, maybe for the series_format).

**Comment by ChristianTremblay** [comment]
I agree it may look more complicated... but I don't like having to make 2 imports just to start the thing... this is a typical 1st cell in Jupyter Notebook.

```
from pyhaystack.client.niagara import Niagara4HaystackSession
import hszinc

session = Niagara4HaystackSession(uri=uri, 
      username=username, 
      password=password,
      http_args={
        "debug": True,
        "tls_verify": False,
        "insecure_requests_warning": False,
         },
      grid_format=hszinc.MODE_JSON,
      pint=True)
```

Probably no big deal, but I think starting off pyhaystack should be possible without relying on special imports to deal with arguments... `'json'`clearly tells what we need. `hszinc.MODE_JSON`... I mean, it is not easy enough for a user to know that we need a special import (which turn down to be a simple `str` anyway...)


This is easier to document and explain : 

```
from pyhaystack.client.niagara import Niagara4HaystackSession

session = Niagara4HaystackSession(uri=uri, 
      username=username, 
      password=password,
      http_args={
        "debug": True,
        "tls_verify": False,
        "insecure_requests_warning": False,
         },
      grid_format='json',
      pint=True)
```
The complexity is added to the code but  we simplify the user task...

I'm may be getting old and grumpy though...

**Comment by ChristianTremblay** [comment]
Enough...
Your proposal is perfect for now. Should have merged it wayyyyyy before.

Thanks for your contribution

**Pull request merged**
